
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
import "interfaceGame.sol";

contract Game is interfaceGame {
    
    uint defence;
    uint health;
    address killerAddr;
// принять атаку
    function acceptAttack(uint aPower) external override{

       uint damage;
       if (defence <= aPower){
           damage = aPower - defence;
       }else{
           damage = 0;
       }

       if (health >= damage) {
           health=health-damage;
       }else{
           health = 0;
       }
       
       if(health <= 0){
         death(msg.sender);  
       }
       tvm.accept();
    }
    
    function death (address enemyAddr) public  {
        // обработка гибели (вызов метода самоунечтожения)
        killerAddr = enemyAddr;
        enemyAddr.transfer(0, true, 128);
        destruction();
        tvm.accept();
    }

    function live() public view returns (bool){
        if (health>0){
            return true;
        }else{
            return false;
        }

    }

    function destruction() public virtual{
        // самоуничтожение        
    }

    function getDefence () public view returns (uint) {
        return defence;
    }

    function getHealth () public view returns (uint) {
        return health;
    }
}