
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
interface interfaceGame {
 function acceptAttack(uint aPower) external;   
}

interface  unitInt{
    function deathBase(address enemyAddr) external;
//    function getAttackPower() external view returns(uint);
}

/* */