
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "Game.sol";
import "baza.sol";

contract unit is Game {

address bazaAddr;
uint attackPower;
string uType;


    function attack(interfaceGame enemyAddr) public view{
        if (health > 0){
            enemyAddr.acceptAttack(attackPower);
        }
        tvm.accept();
    }

    function getAttackPower() public view returns (uint) {
        return attackPower;
    }
    
    modifier onlyBase {
        require(msg.sender == bazaAddr);
        _;
    }

    function deathBase (address enemyAddr) public onlyBase{
        // гибель от базы
        health=0;
        death(enemyAddr);
        tvm.accept();
    }

    function destruction() public override{
        // самоуничтожение + убрать с базы
        attackPower = 0;
        defence = 0;
        baza(bazaAddr).delUnit();        
    }
}
